version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongodb:
    image: mongo:5.0.22
    restart: always
    ports:
      - 27017:27017
