@host=http://localhost:1001
@token=
@id=5


### test server
GET {{host}}

####============================ Departments =========================================
GET {{host}}/api/dep
####
GET {{host}}/api/dep/6

### Add a Department
POST {{host}}/api/dep
Content-Type: application/json

{
    "dept_name": "Data Science",
    "dept_address": "Campus"
}

### Edit Department
PUT {{host}}/api/dep/{{id}}
Content-Type: application/json

{
     "dept_name": "Cyber Security",
    "dept_address": "HQ"
}
### Delete Department
DELETE {{host}}/api/dep/{{id}}


####============================ JobRoles =========================================
GET {{host}}/api/job

### Get Job
GET {{host}}/api/job/{{id}}

### Add a Job
POST {{host}}/api/job/
Content-Type: application/json

{
    "pos_name": "Sr. Software Dev",
    "pos_descrption": "Oversee"
}
### Edit Job
PUT {{host}}/api/job/8
Content-Type: application/json

{
    "pos_name": "Senior Designer",
    "pos_descrption": "Oversee Designs from the team"
}
### Delete Job
DELETE {{host}}/api/job/9

####============================ Employee =========================================
GET {{host}}/api/emp

### Get Employee
GET {{host}}/api/emp/3

### Add a Employee
POST {{host}}/api/emp
Content-Type: application/json

{
    "emp_name": "Zolani",
    "emp_surnme": "Ngxatha",
    "emp_DOB": "2000-12-01",
    "emp_email": "zoe@gmail.com",
    "emp_hired_date": "2021-10-31",
    "emp_Salary": 28000.00,
    "dept_id": 1,
    "pos_id":1
}
### Edit Employee
PUT {{host}}/api/emp/5
Content-Type: application/json

{
    "emp_name": "Aphelele",
    "emp_surnme": "Fassi",
    "emp_DOB": "2000-12-01T10:00:00Z",
    "emp_email": "zoe@gmail.com",
    "emp_hired_date": "2021-10-31T10:00:00Z",
    "emp_Salary": "28000.00",
    "dept_id": 3,
    "pos_id": 2
}
### Delete Employee
DELETE http://localhost:1001/api/emp/10


###  
GET {{host}}/api/dep_pos/