####
GET http://localhost:1002

###
GET http://localhost:1002/api/admin

###
POST http://localhost:1002/api/admin/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Pass123!"
}
###
POST http://localhost:1002/api/admin/register
Content-Type: application/json

{
    "username": "Admin",
    "email": "admin@gmail.com",
    "password": "Pass123!"
}